### ISSUE TITLE
Cannot push

### ISSUE THREAD

**Issue by tomitatsu** [pinchih/CS578-Final-Project#1]
tomitatsu:~/workspace (master) $ git push -u origin master
remote: Permission to pinchih/CS578-Final-Project.git denied to tomitatsu.
fatal: unable to access 'https://tomitatsu@github.com/pinchih/CS578-Final-Project.git/': The requested URL returned error: 403

**Comment by pinchih** [comment]
I think I have to add you as a contributor first. I will do that now.

**Comment by tomitatsu** [comment]
Thanks! I've done! You can see our code here.
